### ISSUE TITLE
Mesa's Meson errors out

### ISSUE THREAD

**Issue by ms178** [JonasToth/llvm-bolt-builds#4]
Hi Jonas,

I am facing issues with a successfully LTO+PGO+BOLTed LLVM using your scripts with some small adjustements. I've tried to compile Mesa-git with it but its Meson build system errors out with the LLVM dependancy missing.

```
WARNING: Ignoring LLVM CMake dependency because dynamic was requested
llvm-config found: YES (/home/marcus/toolchain/llvm/stage2-prof-use-lto/install/bin/llvm-config) 15.0.0
Run-time dependency LLVM (modules: amdgpu, bitreader, bitwriter, core, engine, executionengine, instcombine, ipo, mcdisassembler, mcjit, native, scalaropts, transformutils, coroutines) found: NO (tried cmake and config-tool)
Looking for a fallback subproject for the dependency llvm (modules: bitwriter, engine, mcdisassembler, mcjit, core, executionengine, scalaropts, transformutils, instcombine, amdgpu, native, bitreader, ipo)
Building fallback subproject with default_library=shared

mesa/meson.build:1759:2: ERROR: Neither a subproject directory nor a llvm.wrap file was found.
```

These are the adjustments:

``` 
-DLLVM_POLLY_LINK_INTO_TOOLS=ON \
-DLLVM_ENABLE_RUNTIMES="openmp" \
-DOPENMP_ENABLE_LIBOMPTARGET=OFF \
-DLLVM_TARGETS_TO_BUILD="AMDGPU;X86" \   
-D LLVM_ENABLE_PROJECTS="clang;lld;polly;compiler-rt;clang-tools-extra" \
-D LLVM_BUILD_LLVM_DYLIB=ON \
-D LLVM_LINK_LLVM_DYLIB=ON \
-D CLANG_LINK_CLANG_DYLIB=ON \
```
... and though it compiles fine with BOLT (without perf) there still seems to be something missing. As I'd like to use the optimized toolchain as a full replacement of my system compiler, I'd be glad if you could update the scripts for this usage scenario if there is no technical limitation preventing this.

This is what llvm-config tells me of my components:

```
llvm-config --components
aggressiveinstcombine all all-targets amdgpu amdgpuasmparser amdgpucodegen amdgpudesc amdgpudisassembler amdgpuinfo amdgputargetmca amdgpuutils analysis asmparser asmprinter binaryformat bitreader bitstreamreader bitwriter cfguard codegen core coroutines coverage debuginfocodeview debuginfodwarf debuginfogsym debuginfomsf debuginfopdb demangle dlltooldriver dwarflinker dwp engine executionengine extensions filecheck frontendopenacc frontendopenmp fuzzercli fuzzmutate globalisel instcombine instrumentation interfacestub interpreter ipo irreader jitlink libdriver lineeditor linker lto mc mca mcdisassembler mcjit mcparser mirparser native nativecodegen objcarcopts objcopy object objectyaml option orcjit orcshared orctargetprocess passes profiledata remarks runtimedyld scalaropts selectiondag support symbolize tablegen target textapi transformutils vectorize windowsdriver windowsmanifest x86 x86asmparser x86codegen x86desc x86disassembler x86info x86targetmca xray
```

**Comment by JonasToth** [comment]
to be honest, i don't have time for this and I am not even sure on how to start with something like this.

I guess, that the easiest way to get the optimized LLVM builds is to actually integrate those build steps into the distribution builds instead of trying to get those builds into the distribution. the stages the presented scripts perform are mostly data-gathering.
it might be viable to run the custom builds scripts to produce the PGO + perf reports and then just feed them into the distribution builds.

i don't know what is still missing for your system, but the installation done with my scripts are likely not proper distribution installation. thats something everyone adds a bit of pepper for everything to work out.

maybe @ptr1337 has better understanding/advice.

**Comment by ptr1337** [comment]
Hey @ms178 , 
seems like youre also arch user, I did fight also with that.
First using:
```
-D LLVM_BUILD_LLVM_DYLIB=ON \
-D LLVM_LINK_LLVM_DYLIB=ON \
-D CLANG_LINK_CLANG_DYLIB=ON \
```
Gave me nearly none performance boost if boolting a toolchain.
The issue with mesa i did face also all time, but also got it one time fixed but im not sure how I did fix it actually, since mesa uses llvm as pipe it is depend on it as the system toolchain.

Actually you should not limit the targets, it should build all targets. So just remove it or use -DLLVM_TARGETS_TO_BUILD="all".

Also the install directory needs to be changed to /usr. But as I said, you will probably get into big conflicts. Since also every other packages which is depend on llvm, needs to be rebuilt and configured to your usage.

I will create a PKGBUILD for a system toolchain which can be bolted after building if youre interested in.

**Comment by ptr1337** [comment]
Actually I got also gcc to bolt and working as system compiler without problems. Scripts can be found in the fork from me. 
You need also add:
LLVM_HOST_TRIPLE=$CHOST

**Comment by ptr1337** [comment]
Actually here some stuff about that.
https://github.com/visit-dav/visit/issues/3159
https://gitlab.freedesktop.org/mesa/mesa/-/issues/1945

**Comment by JonasToth** [comment]
as a general remark, if you want a faster mesa, you would need to train the builds for mesa as well. so GPU usage and the proper backends are tracked. you would probably get a bit of speed up because the common datastructures/algorithms became a bit faster. but for the best speed up you need to train  with mesa usage.

**Comment by ptr1337** [comment]
Actually this gives you the ability to pgo mesa easily:
https://github.com/Frogging-Family/mesa-git

Also you can bolt different binarys/.so files with bolt to improve the performance of mesa.

**Comment by ms178** [comment]
I already had some success with a PGOed Mesa in the past, unfortunately not on Arch Linux that I use nowadays as my daily driver. It was also quite involved to get proper profiles. But I simply haven't figured out yet how to integrate that with a makepkg / PKGBUILD-centric build process. Thanks for the pointer to that repo, I might try a PGOed Mesa on Arch as a next project.

**Comment by JonasToth** [comment]
How do you want to proceed on this issue?
I can not help, but its ok to keep the issue open. If you have some success, you could give a short link/explanation on what to do.

If you perform changes on the build script, I am happy to merge them if it still works afterwards.

**Comment by ms178** [comment]
@JonasToth I will keep an eye on improvements to BOLT, maybe the current limitation will be lifted in the future. But I'll close this issue as there is nothing you can do, really.

By the way, using the PKGBUILD provided by ptr1337 worked great for Mesa. It is really easy to get PGO to run there.

**Comment by ptr1337** [comment]
Hey @ms178 ,

Check out that script:
https://github.com/ptr1337/llvm-bolt-scripts/blob/master/bolt-anything.bash

With that you can bolt really mostly everything, mesa works. dynamic linked llvm works, ...
Just get a bit more into in and understand what bolt does then you will have much fun with it.

**Comment by ms178** [comment]
@ptr1337 Thanks for the hint, as always! I'll try it out soon. :)
